### ISSUE TITLE
Marking multiple external libs with --external

### ISSUE THREAD

**Issue by marina-mosti** [posva/rollit#1]
When using rollit with the `--external` flag, it only seems to work when adding a single lib.
For example:

`rollit --external vue` will correctly remove Vue from package

`rollit --external @vuelidate/core` will correctly remove @vuelidate/core imports from the package

However: 

`rollit --external vue,@vuelidate/core` will not work at all, it doesn't remove either.

`rollit --external vue, @vuelidate/core` with a space will only remove vuelidate

`rollit --external @vuelidate/core, vue` will only remove vue

**Comment by posva** [comment]
Does multiple external argument work? I think that was the syntax

**Comment by marina-mosti** [comment]
🤦‍♀️ oops
Thanks!!
